# Generated by Django 5.2.12 on 2026-03-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo Biológico')),
                ('diagnosis', models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('PARKINSON', 'Doença de Parkinson'), ('ELA', 'Esclerose Lateral Amiotrófica - ELA'), ('AVC', 'Acidente Vascular Cerebral - AVC'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Diagnóstico')),
                ('diagnosis_other', models.CharField(blank=True, help_text="Preencher apenas se o diagnóstico for 'Outro'", max_length=255, null=True, verbose_name='Outro Diagnóstico')),
                ('consent_signed', models.BooleanField(default=False, verbose_name='Concordou com o TCLE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('FONACAO', 'Fonação Sustentada'), ('DIADOCOCINESIA', 'Diadococinesia'), ('PALAVRAS', 'Palavras Complexas'), ('LEITURA', 'Leitura Padronizada'), ('ESPONTANEA', 'Fala Espontânea')], max_length=20, verbose_name='Tipo de Tarefa')),
                ('audio_file', models.FileField(upload_to='recordings/%Y/%m/', verbose_name='Arquivo de Áudio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
