# Generated by Django 5.2.12 on 2026-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_medico_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração da Doença (meses)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
