# Generated by Django 5.2.12 on 2026-03-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patient_disease_duration_patient_is_active'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_patient' AND column_name='disease_duration') THEN
                    ALTER TABLE core_patient ADD COLUMN disease_duration integer NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_patient' AND column_name='is_active') THEN
                    ALTER TABLE core_patient ADD COLUMN is_active boolean NOT NULL DEFAULT TRUE;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        )
    ]
