# Generated by Django 5.2.12 on 2026-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260304_1523'),
    ]

    operations = [

        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='patient',
            name='escort_name',
            field=models.CharField(blank=True, help_text='Preencher apenas se estiver com acompanhante', max_length=255, null=True, verbose_name='Nome do Acompanhante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_escort',
            field=models.BooleanField(default=False, verbose_name='Está com acompanhante?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
    ]
