# Generated by Django 5.2.12 on 2026-03-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_patient_disease_duration_and_more'),
    ]

    operations = [
        # disease_duration e is_active já não existem no banco, remoção ignorada
    ]
