# Generated by Django 5.2.12 on 2026-03-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_patient_disease_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease_duration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
