# Generated by Django 5.2.12 on 2026-03-05 16:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_patient_disease_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecording',
            name='audio_file',
            field=models.FileField(upload_to=core.models.patient_directory_path, verbose_name='Arquivo de Áudio'),
        ),
    ]
