# Generated by Django 5.1.1 on 2026-03-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_patientrecording_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease_duration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
