# Generated by Django 5.1.1 on 2026-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_patient_disease_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('ELA_ESPINHAL', 'ELA espinhal'), ('ELA_BULBAR', 'ELA bulbar'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='patientrecording',
            name='task_type',
            field=models.CharField(choices=[('FONACAO_A', 'Fonação Sustentada (Vogal A)'), ('FONACAO_I', 'Fonação Sustentada (Vogal I)'), ('FONACAO_U', 'Fonação Sustentada (Vogal U)'), ('DIADOCOCINESIA', 'Diadococinesia'), ('PALAVRAS', 'Palavras Complexas'), ('LEITURA', 'Leitura Padronizada'), ('ESPONTANEA', 'Fala Espontânea')], max_length=20, verbose_name='Tipo de Tarefa'),
        ),
    ]
