# Generated by Django 5.1.1 on 2026-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patient_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecording',
            name='task_type',
            field=models.CharField(choices=[('FONACAO_A', 'Fonação Sustentada (Vogal A)'), ('FONACAO_I', 'Fonação Sustentada (Vogal I)'), ('FONACAO_U', 'Fonação Sustentada (Vogal U)'), ('DIADOCOCINESIA', 'Diadococinesia'), ('LEITURA', 'Leitura Padronizada')], max_length=20, verbose_name='Tipo de Tarefa'),
        ),
    ]
