# Generated by Django 5.1.1 on 2026-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_patientrecording_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('ELA_INICIO_BULBAR', 'ELA início bulbar'), ('ELA_INICIO_ESPINHAL', 'ELA início espinhal'), ('ELA_ESPINHAL_BULBAR', 'ELA espinhal e bulbar'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Diagnóstico'),
        ),
    ]
