# Generated by Django 5.1.1 on 2026-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_patient_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alsfrs_bulbar',
            field=models.IntegerField(blank=True, help_text='Soma das perguntas 1 a 3 (0 a 12)', null=True, verbose_name='Escore Bulbar ALSFRS-R (0 a 12)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo Biológico'),
        ),
    ]
