# Generated by Django 5.1.1 on 2026-03-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_patient_alsfrs_bulbar_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alsfrs_total',
            field=models.IntegerField(blank=True, help_text='Soma de todas as perguntas (0 a 48)', null=True, verbose_name='Escore Total ALSFRS-R (0 a 48)'),
        ),
    ]
